import { icon } from './icons'
type Mode='standard'|'currency'|'split'
type Item={id:string;expression:string;result:number;createdAt:string;mode:Mode}
export type CalculatorContext={exchangeRate:number;travelers:number}
const KEY='da-nang-calculator-history-v2';let expression='',display='0',fresh=false,mode:Mode='standard',resultCurrency:'THB'|'VND'='THB',ctx:CalculatorContext={exchangeRate:760,travelers:4}
const history=():Item[]=>{try{return JSON.parse(localStorage.getItem(KEY)||'[]') as Item[]}catch{return[]}}
const save=(items:Item[])=>localStorage.setItem(KEY,JSON.stringify(items.slice(0,50)))
const fmt=(n:number)=>new Intl.NumberFormat('th-TH',{maximumFractionDigits:8}).format(n)

/** Safe arithmetic parser; intentionally supports numbers and + - * / ( ) only. */
export function calculateExpression(source:string):number{
  const clean=source.replaceAll('×','*').replaceAll('÷','/').replaceAll('−','-').replace(/\s/g,'')
  const tokens=clean.match(/\d*\.?\d+|[()+\-*/]/g)||[]
  if(!clean||tokens.join('')!==clean)throw Error('invalid')
  let i=0
  const atom=():number=>{const t=tokens[i++];if(t==='('){const n=sum();if(tokens[i++]!==')')throw Error('invalid');return n}if(t==='-')return-atom();const n=Number(t);if(!Number.isFinite(n))throw Error('invalid');return n}
  const product=():number=>{let n=atom();while(tokens[i]==='*'||tokens[i]==='/'){const op=tokens[i++],r=atom();if(op==='/'&&r===0)throw Error('zero');n=op==='*'?n*r:n/r}return n}
  const sum=():number=>{let n=product();while(tokens[i]==='+'||tokens[i]==='-'){const op=tokens[i++],r=product();n=op==='+'?n+r:n-r}return n}
  const n=sum();if(i!==tokens.length||!Number.isFinite(n))throw Error('invalid');return n
}
const key=(label:string,value:string,klass='')=>`<button class="calc-key ${klass}" type="button" data-calc-value="${value}" aria-label="${label}">${label}</button>`
function historyHtml(){const items=history();if(!items.length)return `<div class="empty">${icon('calculator',34)}<strong>ยังไม่มีประวัติ</strong><span>ผลลัพธ์จะบันทึกเมื่อกดเท่ากับ</span></div>`;return items.map(x=>`<div class="history-line"><button class="history-item" type="button" data-history-id="${x.id}"><span><strong>${x.expression}</strong><small>${new Intl.DateTimeFormat('th-TH',{dateStyle:'medium',timeStyle:'short'}).format(new Date(x.createdAt))}</small></span><b>${fmt(x.result)}</b></button><button class="icon-btn" type="button" data-remove-history="${x.id}" aria-label="ลบรายการนี้">${icon('trash')}</button></div>`).join('')}
function toolHtml(){if(mode==='currency')return `<div class="calc-tools"><label>แปลงจาก <select id="convertFrom" class="select"><option>THB</option><option>VND</option></select></label><label>อัตราแลกเปลี่ยน <span class="rate-input"><small>1 THB =</small><input id="calculatorExchangeRate" class="input" type="number" inputmode="decimal" min="1" step="0.01" value="${ctx.exchangeRate}" aria-label="อัตราแลกเปลี่ยน 1 บาทเป็นดอง"><small>VND</small></span></label><output id="toolResult">กรอกจำนวนแล้วกด =</output></div>`;if(mode==='split')return `<div class="calc-tools"><label>จำนวนคน <input id="splitPeople" class="input" type="number" min="1" step="1" value="${ctx.travelers}"></label><output id="toolResult">กรอกยอดแล้วกด =</output></div>`;return''}
export function calculator(next:CalculatorContext){ctx=next;return `<div class="page-head"><div><h1>เครื่องคิดเลข</h1><p>คำนวณ แปลงสกุลเงิน หารต่อคน และเก็บประวัติในอุปกรณ์นี้</p></div></div><section class="calculator-layout"><article class="card calculator-card"><div class="calc-tabs" role="tablist">${([['standard','ทั่วไป'],['currency','THB / VND'],['split','หารต่อคน']] as const).map(([id,label])=>`<button type="button" role="tab" aria-selected="${mode===id}" class="btn ${mode===id?'primary':''}" data-calc-mode="${id}">${label}</button>`).join('')}</div>${toolHtml()}<div class="calc-screen" aria-live="polite"><div class="calc-expression">${expression||'พร้อมคำนวณ'}</div><output class="calc-result" id="calcResult">${display}</output></div><div class="calc-grid" role="group" aria-label="แป้นเครื่องคิดเลข">${key('ล้าง','clear','utility')}${key('ลบ','backspace','utility')}${key('%','%','utility')}${key('÷','÷','operator')}${key('7','7')}${key('8','8')}${key('9','9')}${key('×','×','operator')}${key('4','4')}${key('5','5')}${key('6','6')}${key('−','-','operator')}${key('1','1')}${key('2','2')}${key('3','3')}${key('+','+','operator')}${key('0','0','zero')}${key('.','.')}${key('=','equals','equals')}</div><div class="calc-actions"><button class="btn" id="copyCalcResult" type="button">คัดลอกผลลัพธ์</button><button class="btn primary" id="resultToExpense" type="button">เพิ่มเป็นค่าใช้จ่าย</button></div></article><article class="card history-card"><div class="section-head"><div><h2>ประวัติการคำนวณ</h2><small>เก็บสูงสุด 50 รายการ</small></div>${history().length?'<button class="btn danger" id="clearCalcHistory" type="button">ล้างทั้งหมด</button>':''}</div><div id="calcHistory">${historyHtml()}</div></article></section>`}
function update(){document.querySelector('#calcResult')!.textContent=display;document.querySelector('.calc-expression')!.textContent=expression||'พร้อมคำนวณ'}
function refresh(){const el=document.querySelector('#calcHistory');if(el)el.innerHTML=historyHtml()}
function evaluate(){try{const original=expression;let result=calculateExpression(expression),label=`${original} =`;resultCurrency='THB';if(mode==='currency'){const from=(document.querySelector('#convertFrom') as HTMLSelectElement).value;resultCurrency=from==='THB'?'VND':'THB';result=from==='THB'?result*ctx.exchangeRate:result/ctx.exchangeRate;label=`${original} ${from} → ${resultCurrency}`;document.querySelector('#toolResult')!.textContent=`${fmt(result)} ${resultCurrency}`}if(mode==='split'){const people=Math.max(1,Math.floor(Number((document.querySelector('#splitPeople') as HTMLInputElement).value)||ctx.travelers));result/=people;label=`${original} ÷ ${people} คน`;document.querySelector('#toolResult')!.textContent=`คนละ ${fmt(result)} บาท`}save([{id:crypto.randomUUID(),expression:label,result,createdAt:new Date().toISOString(),mode},...history()]);expression=String(result);display=fmt(result);fresh=true;refresh();update()}catch{display='คำนวณไม่ได้';fresh=true;update()}}
function input(v:string){if(v==='clear'){expression='';display='0';fresh=false}else if(v==='backspace'){expression=expression.slice(0,-1);display=expression||'0';fresh=false}else if(v==='equals'){evaluate();return}else if(v==='%'){const m=expression.match(/(\d*\.?\d+)$/);if(m){const prefix=expression.slice(0,-m[1].length),base=prefix.match(/^(.*?)([-+])$/)?.[1];expression=prefix+(base?`(${base})*${m[1]}/100`:`${m[1]}/100`);evaluate();return}}else{if(fresh&&/[0-9.]/.test(v))expression='';expression+=v;display=expression;fresh=false}update()}
export function registerCalculatorEvents(redraw:()=>void){document.addEventListener('click',e=>{const t=e.target as HTMLElement,k=t.closest<HTMLElement>('[data-calc-value]');if(k)input(k.dataset.calcValue||'');const tab=t.closest<HTMLElement>('[data-calc-mode]');if(tab){mode=tab.dataset.calcMode as Mode;redraw()}const h=t.closest<HTMLElement>('[data-history-id]');if(h){const x=history().find(v=>v.id===h.dataset.historyId);if(x){expression=String(x.result);display=fmt(x.result);fresh=true;update()}}const remove=t.closest<HTMLElement>('[data-remove-history]');if(remove){save(history().filter(x=>x.id!==remove.dataset.removeHistory));refresh()}if(t.closest('#clearCalcHistory')&&confirm('ล้างประวัติทั้งหมดหรือไม่?')){save([]);refresh()}if(t.closest('#copyCalcResult'))navigator.clipboard.writeText(expression||display).catch(()=>undefined);if(t.closest('#resultToExpense')){const amount=Number(expression);if(Number.isFinite(amount))window.dispatchEvent(new CustomEvent('calculator-create-expense',{detail:{amount,currency:resultCurrency}}))}});document.addEventListener('input',e=>{const target=e.target as HTMLInputElement;if(target.id==='calculatorExchangeRate'){const rate=Number(target.value);if(Number.isFinite(rate)&&rate>0)ctx.exchangeRate=rate}});document.addEventListener('change',e=>{const target=e.target as HTMLInputElement;if(target.id==='calculatorExchangeRate'){const rate=Number(target.value);if(Number.isFinite(rate)&&rate>0)window.dispatchEvent(new CustomEvent('calculator-exchange-rate-change',{detail:{exchangeRate:rate}}))}});document.addEventListener('keydown',e=>{if(!document.querySelector('.calculator-card')||(e.target as HTMLElement).matches('input,textarea,select'))return;if(/^[-0-9.+*/()]$/.test(e.key)){e.preventDefault();input(e.key.replace('*','×').replace('/','÷'))}else if(e.key==='Enter'||e.key==='='){e.preventDefault();input('equals')}else if(e.key==='Backspace'){e.preventDefault();input('backspace')}else if(e.key==='Escape'){e.preventDefault();input('clear')}})}
