export const categories = ['Flights','Accommodation','Transportation','Food','Activities','Shopping','Other'] as const
export type Category = typeof categories[number]
export type Currency = 'THB' | 'VND'
export type Status = 'paid' | 'planned'
export type Person = { id: string; name: string }
export type Expense = { id: string; date: string; dayId?: string | null; item: string; category: Category; amount: number; currency: Currency; payerId: string; status: Status; note: string }
export type DayPlace = { id: string; name: string; address: string; mapUrl: string }
export type DayPlan = { id: string; date: string; title: string; activities: string; budgetTHB: number; places: DayPlace[] }
export type TripEssentialKind = 'flight' | 'stay' | 'emergency'
export type TripEssential = { id: string; kind: TripEssentialKind; title: string; details: string; bookingRef: string; address: string; phone: string; mapUrl: string }
export type PackingCategory = 'documents' | 'clothes' | 'medicine' | 'equipment' | 'personal'
export type PackingItem = { id: string; category: PackingCategory; name: string; packed: boolean }
export type Settings = { tripName: string; startDate: string; endDate: string; budgetTHB: number; exchangeRate: number; travelers: Person[] }
export type AppData = { settings: Settings; expenses: Expense[]; days: DayPlan[]; tripEssentials: TripEssential[]; packingItems: PackingItem[]; pinnedNote: string }
